// <auto-generated />
using System;
using FoodLover.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodLover.Data.Migrations
{
    [DbContext(typeof(FoodLoverDbContext))]
    partial class FoodLoverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoodLover.Model.CategoryByMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("CategoryByMeals");
                });

            modelBuilder.Entity("FoodLover.Model.CategoryByProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FoodLover.Model.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryByMealId");

                    b.Property<int>("CategoryByProductId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Prepare")
                        .IsRequired();

                    b.Property<TimeSpan>("TimeForPrepare");

                    b.HasKey("Id");

                    b.HasIndex("CategoryByMealId");

                    b.HasIndex("CategoryByProductId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("FoodLover.Model.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Image")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("FoodLover.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MealId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FoodLover.Model.Meal", b =>
                {
                    b.HasOne("FoodLover.Model.CategoryByMeal", "CategoryByMeals")
                        .WithMany("Meals")
                        .HasForeignKey("CategoryByMealId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FoodLover.Model.CategoryByProducts", "CategoryByProducts")
                        .WithMany("Meals")
                        .HasForeignKey("CategoryByProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FoodLover.Model.Product", b =>
                {
                    b.HasOne("FoodLover.Model.Meal")
                        .WithMany("Products")
                        .HasForeignKey("MealId");
                });
#pragma warning restore 612, 618
        }
    }
}
